travel_journal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from travel_journal import settings
from accounts.views import SignUpView, user_logout, profile_update, delete_user, profile_view
from viewer.views import home, get_filtered_entries, EntryCreateView, EntryDetailView, EntryUpdateView, \
    EntryDeleteView, search_results, ImageUploadView, ImageDeleteView, EntriesEditView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', home, name='home'),

    path('entries/', get_filtered_entries, name='entries'),
    path('entries/create', EntryCreateView.as_view(), name='entry_create'),
    path('entry/<pk>', EntryDetailView.as_view(), name='entry_detail'),
    path('entry/<pk>/update', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<pk>/delete', EntryDeleteView.as_view(), name='entry_delete'),
    path('entry/<pk>/image_upload', ImageUploadView.as_view(), name='image_upload'),
    path('entries_edit', EntriesEditView.as_view(), name='edit_panel'),

    path('image_delete/<pk>', ImageDeleteView.as_view(), name='image_delete'),

    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/logout/', user_logout, name='logout'),
    path('accounts/update/', profile_update, name='profile_update'),
    path('accounts/profile/<username>', profile_view, name='profile'),
    path('accounts/delete/', delete_user, name='delete_account'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('faq', TemplateView.as_view(template_name='faq.html'), name='faq'),
    path('contact', TemplateView.as_view(template_name='contact.html'), name='contact'),

    path('search/', search_results, name='search_results'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

triptrack/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from triptrack import settings
from accounts.views import SignUpView, user_logout, profile_update, delete_user, profile_view
from viewer.views import home, get_filtered_entries, EntryCreateView, EntryDetailView, EntryUpdateView, \
    EntryDeleteView, search_results, ImageUploadView, ImageDeleteView, EntriesEditView

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),

    path('', home, name='home'),

    path('entries/', get_filtered_entries, name='entries'),
    path('entries/create', EntryCreateView.as_view(), name='entry_create'),
    path('entry/<pk>', EntryDetailView.as_view(), name='entry_detail'),
    path('entry/<pk>/update', EntryUpdateView.as_view(), name='entry_update'),
    path('entry/<pk>/delete', EntryDeleteView.as_view(), name='entry_delete'),
    path('entry/<pk>/image_upload', ImageUploadView.as_view(), name='image_upload'),
    path('entries_edit', EntriesEditView.as_view(), name='edit_panel'),

    path('image_delete/<pk>', ImageDeleteView.as_view(), name='image_delete'),

    path('accounts/signup/', SignUpView.as_view(), name='signup'),
    path('accounts/logout/', user_logout, name='logout'),
    path('accounts/update/', profile_update, name='profile_update'),
    path('accounts/profile/<username>', profile_view, name='profile'),
    path('accounts/delete/', delete_user, name='delete_account'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('faq', TemplateView.as_view(template_name='faq.html'), name='faq'),
    path('contact', TemplateView.as_view(template_name='contact.html'), name='contact'),

    path('search/', search_results, name='search_results'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if not settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewer/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import ForeignKey


# Create your models here.
class Country(models.Model):
    country = models.CharField(max_length=100, null=False, blank=False)
    code = models.CharField(max_length=3, null=False, blank=False)

    class Meta:
        verbose_name_plural = "Countries"
        ordering = ["code"]

    def __str__(self):
        return self.country

    def __repr__(self):
        return f"Country(country={self.country}, code={self.code})"

class Place(models.Model):
    place = models.CharField(max_length=100, null=False, blank=False)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, null=False, blank=False)

    class Meta:
        verbose_name_plural = "Places"
        ordering = ["place"]

    def __str__(self):
        return self.place

    def __repr__(self):
        return f"Place(place={self.place})"

class Transport(models.Model):
    type = models.CharField(max_length=100, null=False, blank=False)

    class Meta:
        ordering = ["type"]

    def __str__(self):
        return self.type

    def __repr__(self):
        return f"Transport(type={self.type})"

class Weather(models.Model):
    type = models.CharField(max_length=100, null=False, blank=False)

    class Meta:
        ordering = ["type"]

    def __str__(self):
        return self.type

    def __repr__(self):
        return f"Weather(type={self.type})"

class Hashtag(models.Model):
    hashtag = models.CharField(max_length=100, null=False, blank=False)

    class Meta:
        verbose_name_plural = "Hashtags"
        ordering = ["hashtag"]

    def __str__(self):
        return self.hashtag

    def __repr__(self):
        return f"Hashtag(hashtag={self.hashtag})"

CURRENCY_CHOICES = (
    ("AUD", "Australian dollar (AUD)"),
    ("CNY", "Chinese yuan (CNY)"),
    ("CZK", "Czech koruna (CZK)"),
    ("EUR", "Euro (EUR)"),
    ("GBP", "Pound sterling (GBP)"),
    ("USD", "U.S. dollar (USD)")
)

RATING_CHOICES = (
    (1, "⭐"),
    (2, "⭐⭐"),
    (3, "⭐⭐⭐"),
    (4, "⭐⭐⭐⭐"),
    (5, "⭐⭐⭐⭐⭐")
)

class Entry(models.Model):
    entry_name = models.CharField(max_length=100, null=False, blank=False)
    author = ForeignKey(User, on_delete=models.CASCADE, null=False, blank=False)
    description = models.TextField(null=False, blank=False)
    country = models.ManyToManyField(Country, blank=False)
    place = models.ManyToManyField(Place, blank=False)
    arrival_date = models.DateField(null=True, blank=True)
    departure_date = models.DateField(null=True, blank=True)
    stayed_for = models.IntegerField(null=True, blank=True)
    transport = models.ManyToManyField(Transport, blank=True)
    cost = models.DecimalField(max_digits=7, decimal_places=2, null=True, blank=True)
    currency = models.CharField(max_length=3, choices=CURRENCY_CHOICES, default="USD", null=True, blank=True)
    weather = models.ManyToManyField(Weather, blank=True)
    rating = models.IntegerField(choices=RATING_CHOICES, default=1, null=True, blank=True)
    hashtag = models.ManyToManyField(Hashtag, blank=True)
    is_private = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = "Entries"
        ordering = ["arrival_date"]

    def __str__(self):
        return self.entry_name

    def __repr__(self):
        return f"Entry(entry_name={self.entry_name})"

    def calculate_duration(self):
        if self.arrival_date and self.departure_date:
            duration = self.departure_date - self.arrival_date
            return duration.days

class Image(models.Model):
    image = models.ImageField(null=False, blank=False)
    description = models.TextField(null=True, blank=True)
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return self.image.name

    def __repr__(self):
        return f"Image(image={self.image})"

viewer/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Max
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from django.contrib.auth.models import User

from viewer.forms import EntryCreateForm, ImageUploadForm
from viewer.models import Entry, Country, Place, Image


def home(request):
    return render(request, "home.html")


class EntriesEditView(UserPassesTestMixin, ListView):
    template_name = "edit_panel.html"
    model = Entry
    context_object_name = 'entries_list'


    def test_func(self):
        """Page will be shown only to users with editor privileges or to administrators"""
        return self.request.user.is_superuser or self.request.user.groups.filter(name='editor').exists()


class EntryCreateView(LoginRequiredMixin, CreateView):
    template_name = 'entry_form.html'
    form_class = EntryCreateForm

    def form_valid(self, form):
        """Upon receiving a valid post request, the current user will be added to the new entry's author field.
        The user will then be directed to upload images
        """
        form.instance.author = self.request.user
        entry = form.save()
        return redirect(reverse('image_upload', kwargs={'pk': entry.pk}))


class EntryUpdateView(UserPassesTestMixin, UpdateView):
    template_name = 'entry_form.html'
    model = Entry
    form_class = EntryCreateForm

    def test_func(self):
        """Page will only be shown to the entry's author or to users with editor privileges"""
        entry = self.get_object()
        is_editor_or_superuser = self.request.user.is_superuser or self.request.user.groups.filter(name='editor').exists()
        return entry.author == self.request.user or is_editor_or_superuser

    def get_context_data(self, **kwargs):
        """This allows already existing places and hashtags to show up on the update page"""
        context = super().get_context_data(**kwargs)
        entry = self.object
        context['saved_places'] = entry.place.all()
        context['saved_countries'] = entry.country.all()
        context['saved_hashtags'] = entry.hashtag.all()
        return context

    def form_valid(self, form):
        """Upon successful update, the image upload page will be shown"""
        entry = form.save()
        return redirect(reverse('image_upload', kwargs={'pk': entry.pk}))


class EntryDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'entry_delete.html'
    model = Entry
    success_url = reverse_lazy('entries')

    def test_func(self):
        """Page will only be shown to the entry's author or to users with editor privileges"""
        entry = self.get_object()
        is_editor_or_superuser = self.request.user.is_superuser or self.request.user.groups.filter(name='editor').exists()
        return entry.author == self.request.user or is_editor_or_superuser

class EntryDetailView(UserPassesTestMixin, DetailView):
    template_name = 'entry_detail.html'
    model = Entry
    context_object_name = 'entry'

    def test_func(self):
        """Entries marked as private will only be shown to the entry's author or to users with editor privileges"""
        entry = self.get_object()
        is_editor_or_superuser = self.request.user.is_superuser or self.request.user.groups.filter(name='editor').exists()
        return not entry.is_private or entry.author == self.request.user or is_editor_or_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        entry = self.object

        # If an entry has both an arrival and departure date, the duration of the trip is calculated
        if entry.arrival_date and entry.departure_date:
            duration = (entry.departure_date - entry.arrival_date).days
        else:
            duration = None

        # FontAwesome icons to be shown for each weather and transport selection
        weather_icons = {
            "overcast": "cloud",
            "rain": "cloud-rain",
            "sun": "sun",
            "storm": "bolt",
            "wind": "wind",
            "snow": "snowflake",
            "fog": "smog",
            "hail": "cloud-meatball",
            "chill": "temperature-low",
            "hot": "temperature-high"
        }

        transport_icons = {
            "plane": "plane",
            "train": "train",
            "metro": "train-subway",
            "tram": "train-tram",
            "car": "car",
            "bus": "bus",
            "cable_car": "cable-car",
            "on_foot": "person-walking",
            "boat": "sailboat",
            "bicycle": "bicycle",
            "motorcycle": "motorcycle",
            "horse": "horse"
        }

        weather_icon_list = []
        for weather in entry.weather.all():
            weather_icon_list.append(weather_icons.get(weather.type, "question"))

        transport_icon_list = []
        for transport in entry.transport.all():
            transport_icon_list.append(transport_icons.get(transport.type, "question"))

        context['stayed_for'] = duration
        context['weather_icon_list'] = weather_icon_list
        context['transport_icon_list'] = transport_icon_list

        return context

def get_countries_and_places():
    countries = Country.objects.all()
    places = Place.objects.all()
    return countries, places

def get_filtered_entries(request):
    """Used by the filter function in the 'view trips' view"""
    entries = Entry.objects.filter(is_private=False).distinct()

    countries = entries.values_list('country__country', flat=True).distinct()
    places = entries.values_list('place__place', flat=True).distinct()
    max_cost = entries.aggregate(Max('cost'))['cost__max'] or 0
    currencies = set(entry.currency.strip() for entry in entries)

    arrival_date = request.GET.get('arrival_date')
    departure_date = request.GET.get('departure_date')
    rating = request.GET.get('rating')
    selected_country = request.GET.get('country')
    selected_place = request.GET.get('place')
    selected_cost = request.GET.get('cost')
    selected_currency = request.GET.get('currency')
    selected_weather = request.GET.getlist('weather')
    selected_transport = request.GET.getlist('transport')
    hashtags_str = request.GET.get('hashtags')

    if arrival_date:
        entries = entries.filter(arrival_date=arrival_date)
    if departure_date:
        entries = entries.filter(departure_date=departure_date)
    if rating:
        entries = entries.filter(rating=rating)
    if selected_country:
        entries = entries.filter(country__country=selected_country)
    if selected_place:
        entries = entries.filter(place__place=selected_place)
    if selected_cost:
        entries = entries.filter(cost__lte=selected_cost)
    if selected_currency:
        entries = entries.filter(currency=selected_currency)
    if selected_weather:
        entries = entries.filter(weather__type__in=selected_weather)
    if selected_transport:
        entries = entries.filter(transport__type__in=selected_transport)
    if hashtags_str:
        hashtags = hashtags_str.split(',')
        entries = entries.filter(hashtag__hashtag__in=hashtags).distinct()

    return render(request, 'entries.html', {
        'entries': entries,
        'countries': countries,
        'places': places,
        'max_cost': max_cost,
        'selected_cost': selected_cost,
        'currencies': list(currencies),
    })

def search_results(request):
    query = request.GET.get('query')
    if query:
        entry_results = Entry.objects.filter(is_private=False).filter(
            entry_name__icontains=query
        ) | Entry.objects.filter(is_private=False).filter(
            description__icontains=query
        )
        user_results = User.objects.filter(username__icontains=query) | User.objects.filter(
            profile__display_name__icontains=query
        )
    else:
        entry_results = Entry.objects.none()
        user_results = User.objects.none()

    return render(request, 'search_results.html', {
        'entry_results': entry_results,
        'user_results': user_results,
        'query': query
    })


class ImageUploadView(UserPassesTestMixin, CreateView):
    template_name = 'image_upload.html'
    form_class = ImageUploadForm

    def test_func(self):
        """Page will only be shown to the entry's author or to users with editor privileges"""
        entry = Entry.objects.get(pk=self.kwargs['pk'])
        is_editor_or_superuser = self.request.user.is_superuser or self.request.user.groups.filter(name='editor').exists()
        return entry.author == self.request.user or is_editor_or_superuser

    def get_success_url(self):
        """Upon upload, user will stay on the upload page to upload more photos"""
        return reverse_lazy('image_upload', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self, **kwargs):
        """Shows data relating to the entry associated with the images being uploaded"""
        context = super().get_context_data(**kwargs)
        entry = Entry.objects.get(pk=self.kwargs['pk'])
        context['entry_pk'] = entry.pk
        context['entry_name'] = entry.entry_name
        context['entry'] = entry
        return context

    def form_valid(self, form):
        """Upon successful upload, the new image will be associated with the entry specified by the URL"""
        self.object = form.save(commit=False)
        self.object.entry = Entry.objects.get(pk=self.kwargs['pk'])
        self.object.save()
        messages.success(self.request, 'Image was successfully uploaded!')
        return super().form_valid(form)


class ImageDeleteView(UserPassesTestMixin, DeleteView):
    template_name = 'image_delete.html'
    model = Image

    def test_func(self):

viewer/templates/contact.html
{% extends "base.html" %}

{% block title %}
Contact | TripTrack
{% endblock %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center mb-5">Contact Us</h2>

    <div class="row">
        <div class="col-md-12">
            <h4>Get in Touch</h4>
            <p>If you have any questions, suggestions, or need support, feel free to contact us. We're here to help and make your experience with TripTrack as smooth as possible!</p>

            <p><strong>Email:</strong> support@triptrack.com</p>
            <p><strong>Phone:</strong> +123 456 789</p>
            <p><strong>Address:</strong> 123 Travel Lane, Wanderlust City, Country</p>

            <h4 class="mt-5">Frequently Asked Questions</h4>
            <p>Have a question? Check out our <a href="{% url 'faq' %}">FAQ</a> page for common inquiries and answers. We cover everything from account setup to trip management and everything in between.</p>

        </div>
    </div>
</div>
{% endblock %}

viewer/templates/edit_panel.html
{% extends "base.html" %}

{% block title %}
Entry edit panel | TripTrack
{% endblock %}

{% block content %}
<h1>All Trips</h1>

{% if entries_list %}
    <ul>
        {% for entry in entries_list %}
            <li>
                <a href="{% url 'entry_detail' entry.pk %}">{{ entry.entry_name }}</a>
                    <a href="{% url 'entry_update' entry.pk %}" class="ml-2">
                        <i class="fa-solid fa-pen"></i>
                    </a>
                    <a href="{% url 'entry_delete' entry.pk %}" class="ml-2">
                        <i class="fa-solid fa-trash"></i>
                    </a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No trips.</p>
{% endif %}
{% endblock %}

viewer/templates/entries.html
{% extends "base.html" %}

{% block title %}
Popular trips | TripTrack
{% endblock %}

{% block content %}
<h1 class="display-4">Popular trips</h1>
<div class="h5 font-weight-normal mb-3 mt-3 text-">Looking for inspiration for your next trip? Explore our collection of entries filled with
    travel stories, tips, and beautiful destinations. Whether you're planning a weekend getaway or a long vacation,
    you're sure to find ideas that spark your wanderlust here.</div>

<div class="d-flex justify-content-between">
    <a href="#" class="mb-4" data-toggle="collapse" data-target="#filterForm" aria-expanded="false" aria-controls="filterForm">
        Show/Hide Filters
    </a>
    <a href="{% url 'entries' %}" class="mb-4 text-right">Clear Filter</a>
</div>



<!-- Filtrování -->
<div class="collapse" id="filterForm">
    <form method="GET" action="" class="mt-4">
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="country">Country</label>
                <select name="country" id="country" class="form-control">
                    <option value="">-- Choose a country --</option>
                    {% for country in countries %}
                        <option value="{{ country }}">{{ country }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group col-md-2">
                <label for="place">Place</label>
                <select name="place" id="place" class="form-control">
                    <option value="">-- Choose a place --</option>
                    {% for place in places %}
                        <option value="{{ place }}">{{ place }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="form-group col-md-2">
                <label>Arrival date</label>
                <input type="date" name="arrival_date" class="form-control">
            </div>

            <div class="form-group col-md-2">
                <label>Departure date</label>
                <input type="date" name="departure_date" class="form-control">
            </div>

            <div class="form-group col-md-3">
                <label>Rating</label>
                <select name="rating" class="form-control">
                    <option value="">-- Choose rating --</option>
                    <option value="1">⭐</option>
                    <option value="2">⭐⭐</option>
                    <option value="3">⭐⭐⭐</option>
                    <option value="4">⭐⭐⭐⭐</option>
                    <option value="5">⭐⭐⭐⭐⭐</option>
                </select>
            </div>

            <div class="form-group col-md-4 d-flex align-items-end">
                <div class="w-75 mr-2">
                    <label for="cost" class="form-label">Cost</label>
                    <input type="number" name="cost" class="form-control"
                           value="{{ selected_cost|default_if_none:'' }}"
                           id="cost"
                    >
                </div>
                <div class="w-25">
                    <label for="currency" class="form-label">Currency</label>
                    <select name="currency" id="currency" class="form-control">
                        <option value="" selected disabled></option>
                        {% for currency in currencies %}
                            <option value="{{ currency }}">{{ currency }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="form-group col-md-2 ml-4">
                <label>Weather</label>
                <div>
                    <span><input type="checkbox" name="weather" value="overcast"><i class="fa-solid fa-cloud" title="Overcast"></i></span>
                    <span><input type="checkbox" name="weather" value="rain"><i class="fa-solid fa-cloud-rain" title="Rain"></i></span>
                    <span><input type="checkbox" name="weather" value="sun"><i class="fa-solid fa-sun" title="Sun"></i></span>
                    <span><input type="checkbox" name="weather" value="storm"><i class="fa-solid fa-bolt" title="Storm"></i></span>
                    <span><input type="checkbox" name="weather" value="wind"><i class="fa-solid fa-wind" title="Wind"></i></span>
                    <span><input type="checkbox" name="weather" value="snow"><i class="fa-solid fa-snowflake" title="Snow"></i></span>
                    <span><input type="checkbox" name="weather" value="fog"><i class="fa-solid fa-smog" title="Fog"></i></span>
                    <span><input type="checkbox" name="weather" value="hail"><i class="fa-solid fa-cloud-meatball" title="Hail"></i></span>
                    <span><input type="checkbox" name="weather" value="chill"><i class="fa-solid fa-temperature-low" title="Chill"></i></span>
                    <span><input type="checkbox" name="weather" value="hot"><i class="fa-solid fa-temperature-high" title="Hot"></i></span>
                </div>
            </div>

            <div class="form-group col-md-3">
                <label>Transport</label>
                <div>
                    <span><input type="checkbox" name="transport" value="plane"><i class="fa-solid fa-plane" title="Plane"></i></span>
                    <span><input type="checkbox" name="transport" value="train"><i class="fa-solid fa-train" title="Train"></i></span>
                    <span><input type="checkbox" name="transport" value="metro"><i class="fa-solid fa-train-subway" title="Metro"></i></span>
                    <span><input type="checkbox" name="transport" value="tram"><i class="fa-solid fa-train-tram" title="Tram"></i></span>
                    <span><input type="checkbox" name="transport" value="car"><i class="fa-solid fa-car" title="Car"></i></span>
                    <span><input type="checkbox" name="transport" value="bus"><i class="fa-solid fa-bus" title="Bus"></i></span><br>
                    <span><input type="checkbox" name="transport" value="cable_car"><i class="fa-solid fa-cable-car" title="Cable car"></i></span>
                    <span><input type="checkbox" name="transport" value="on_foot"><i class="fa-solid fa-person-walking" title="On foot"></i></span>
                    <span><input type="checkbox" name="transport" value="boat"><i class="fa-solid fa-sailboat" title="Boat"></i></span>
                    <span><input type="checkbox" name="transport" value="bicycle"><i class="fa-solid fa-bicycle" title="Bicycle"></i></span>
                    <span><input type="checkbox" name="transport" value="motorcycle"><i class="fa-solid fa-motorcycle" title="Motorcycle"></i></span>
                    <span><input type="checkbox" name="transport" value="horse"><i class="fa-solid fa-horse" title="Horse"></i></span>
                </div>
            </div>

            <!-- Hashtag Filtering -->
            <div class="form-group col-md-2">
                <label>Hashtags</label>
                <div class="input-group mb-3">
                    <input type="text" id="hashtag-input" class="form-control" placeholder="Enter hashtag">
                    <button type="button" class="btn btn-secondary" id="add-hashtag-btn">Add</button>
                </div>

                <div id="hashtag-list" class="mt-2"></div>
                <input type="hidden" name="hashtags" id="hashtags-hidden">
            </div>
        </div>

        <button type="submit" class="btn btn-primary btn-block">Filter</button>
    </form>
</div>

<div>
    <div class="container bg-white p-4 mt-4 border rounded shadow-sm">
        <h3 class="text-secondary">Trips</h3>

        <div class="row">
            {% if entries %}
                {% for entry in entries %}
                    <div class="col-md-6 col-lg-4 mb-4 d-flex entries-page-card">
                        <div class="card shadow-sm h-100 w-100">
                            {% if entry.image_set.first %}
                                <img src="{{ entry.image_set.first.image.url }}" class="card-img-top" alt="Image for {{ entry.entry_name }}">
                            {% endif %}
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title">{{ entry.entry_name }}</h5>
                                <p class="card-text">{{ entry.description|slice:":150" }}...</p>
                                <div class="mt-auto">
                                    <p class="mb-2">
                                        {% for i in "12345" %}
                                            {% if i|add:"0" <= entry.rating %}
                                                <span><i class="fa-solid fa-star yellow-star"></i></span>
                                            {% else %}
                                                <span><i class="fa-regular fa-star yellow-star"></i></span>
                                            {% endif %}
                                        {% endfor %}
                                    </p>
                                    <a href="{% url 'entry_detail' entry.pk %}" class="btn btn-secondary btn-block">View Trip</a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="alert alert-info text-center col-12 mb-4" role="alert">
                     ❗ No results found
                </div>
            {% endif %}
        </div>
    </div>
</div>

{% endblock %}

viewer/templates/image_upload.html
{% extends "base.html" %}

{% block title %}
Upload Image for {{ entry_name }} | TripTrack
{% endblock %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="container d-flex justify-content-center align-items-start">
        <div class="card p-4 mt-5 custom-crd">
            <h3 class="text-center mb-4">Upload image for {{ entry_name }}</h3>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="mb-4">The first uploaded image will be used as a preview of your entry. </div>
                <div class="mb-4">If you do not wish to upload any images, you can just go to your entry. </div>
                <input id="id_submit" type="submit" value="Upload" class="btn btn-primary w-100">
                <div class="text-center">
                    <a href="{% url 'entry_detail' entry_pk %}">Or go to entry</a>
                </div>
            </form>
        </div>
    </div>

    <div class="container mt-5">
        <h4>Uploaded images:</h4>
        <div class="row">
            {% for image in entry.image_set.all %}
                <div class="col-md-3">
                    <div class="card mb-3">
                        <div class="d-flex justify-content-between p-2">
                            <a href="{% url 'image_delete' image.pk %}" class="text-danger">
                                <i class="fa fa-trash" aria-hidden="true"></i> Delete
                            </a>
                        </div>
                        <img src="{{ image.image.url }}" class="card-img-top" alt="Image">
                        <div class="card-body">
                            <p class="card-text">{{ image.description }}</p>
                        </div>
                    </div>
                </div>
            {% empty %}
                <p>No images uploaded yet.</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}